name: CI

on: [ push, workflow_dispatch ]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          sudo cat /proc/$(pidof provisioner)/io
          sudo rustup update stable --no-self-update
          sudo cat /proc/$(pidof provisioner)/io
          
